### ISSUE TITLE
finlandica.fi

### ISSUE THREAD

**Issue by pabl0** [HelsinkiTypeStudio/Finlandica#9]
Your (I assume it's yours?) web site for Finlandica  assumes the user has the font files installed locally and renders using the generic sans-serif fallback typeface if the user does not have it. Why not use CSS @import to load it from your web site or fonts.google.com so most people would see it correctly? It took me a while to figure out why the font looks very differrent from samples in fonts.google.com.

**Comment by niklas-ekholm** [comment]
Thanks for notifying me! This had been overlooked for too long. Better late than never, I hope ┐(‘～` )┌
